name: Small Fix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "auto_var"
          replace: "infxgvar"
          include: "INFINIX/**"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:

          commit_message: 'Auto Fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: ItzSjDude
          commit_user_email: support@itzsjdude.in
          commit_author: ItzSjDude <support@itzsjdude.in>
