name: Small Fix
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }} 
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "is_pika_tg"
          replace: "is_infx_tg"
      - name: Create Pull Request
        uses: stefanzweifel/git-auto-commit-action@v4
        with:

          commit_message: 'Auto Fixes'
          commit_options: '--no-verify'
          branch: main
          repository: .
          commit_user_name: ItzSjDude
          commit_user_email: support@itzsjdude.in
          commit_author: ItzSjDude <support@itzsjdude.in>
